name: 📦 Publish NuGet package

on:
  pull_request: # TODO: remove debug
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  publish:
    name: Pack & publish
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup NuGet
        uses: nuget/setup-nuget@v2

      - name: Pack
        run: nuget pack ProCoSys.jQuery.NestedSortable.nuspec -OutputDirectory ./nupkg

      - name: Push to GitHub Packages
        shell: bash
        run: dotnet nuget push ./nupkg/*.nupkg --source https://nuget.pkg.github.com/equinor/index.json --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
